import { Resend } from 'resend';
import { jsPDF } from 'jspdf';

const resend = new Resend(process.env.RESEND_API_KEY);

interface CallSummaryEmailParams {
  lawyerEmail: string;
  lawyerName: string;
  callerName: string;
  callerPhone: string;
  callerEmail?: string;
  summary: string;
  notes: string;
  legalArea: string;
  petitionType?: string;
  urgencyFlag?: string;
  matterCategory?: string;
  partyRole?: string;
  availabilityLink?: string;
}

function generateTranscriptPdf(params: CallSummaryEmailParams): Buffer {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const addText = (text: string, size: number, style: 'normal' | 'bold' = 'normal', color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      if (y > 275) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += size * 0.45;
    }
    y += 2;
  };

  const addLine = () => {
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
  };

  // Header
  addText('ANDERSON BOWMAN PLLC', 14, 'bold');
  addText('AI Paralegal - Call Transcript & Summary', 10, 'normal', [100, 100, 100]);
  y += 4;
  addLine();

  // Client info
  addText('CLIENT INFORMATION', 10, 'bold', [50, 50, 50]);
  y += 2;
  addText(`Name: ${params.callerName}`, 10);
  addText(`Phone: ${params.callerPhone}`, 10);
  if (params.callerEmail) addText(`Email: ${params.callerEmail}`, 10);
  addText(`Legal Area: ${params.legalArea}`, 10);
  addText(`Date: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`, 10);
  y += 4;
  addLine();

  // Case flags
  if (params.petitionType || params.urgencyFlag || params.matterCategory || params.partyRole) {
    addText('CASE FLAGS', 10, 'bold', [50, 50, 50]);
    y += 2;
    if (params.petitionType)  addText(`Petition Type:    ${params.petitionType}`, 10);
    if (params.matterCategory) addText(`Matter Category:  ${params.matterCategory}`, 10);
    if (params.partyRole)     addText(`Party Role:       ${params.partyRole}`, 10);
    if (params.urgencyFlag)   addText(`Urgency:          ${params.urgencyFlag}`, 10, 'bold', [200, 0, 0]);
    y += 4;
    addLine();
  }

  // Summary
  addText('CALL SUMMARY', 10, 'bold', [50, 50, 50]);
  y += 2;
  addText(params.summary || 'No summary available.', 10);
  y += 4;
  addLine();

  // Detailed notes
  if (params.notes) {
    addText('DETAILED NOTES', 10, 'bold', [50, 50, 50]);
    y += 2;
    addText(params.notes, 9);
    y += 4;
    addLine();
  }

  // Transcript
  if (params.notes && params.notes.includes(':')) {
    addText('CALL TRANSCRIPT', 10, 'bold', [50, 50, 50]);
    y += 2;
    const lines = params.notes.split('\n').filter(Boolean);
    for (const line of lines) {
      const colonIdx = line.indexOf(':');
      if (colonIdx === -1) {
        addText(line, 9);
        continue;
      }
      const role = line.slice(0, colonIdx).trim().toLowerCase();
      const content = line.slice(colonIdx + 1).trim();
      const isAi = role === 'assistant' || role === 'bot' || role === 'ai';
      const label = isAi ? 'AI' : 'Caller';
      addText(`${label}: ${content}`, 9, 'normal', isAi ? [37, 99, 235] : [0, 0, 0]);
    }
  }

  // Footer
  y += 8;
  addText('Generated by AI Paralegal - Privileged & Confidential', 8, 'normal', [150, 150, 150]);

  const arrayBuffer = doc.output('arraybuffer');
  return Buffer.from(arrayBuffer);
}

export async function sendCallSummaryEmail(params: CallSummaryEmailParams): Promise<{ success: boolean; error?: string }> {
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'noreply@example.com';

  try {
    // Generate PDF transcript
    let pdfBuffer: Buffer | null = null;
    try {
      pdfBuffer = generateTranscriptPdf(params);
    } catch (err) {
      console.error('[email] PDF generation failed, sending without attachment:', err);
    }

    const date = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

    await resend.emails.send({
      from: `AI Paralegal <${fromEmail}>`,
      to: params.lawyerEmail,
      subject: `New Prospective Client: ${params.callerName} - ${params.legalArea}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1a1a1a;">New Prospective Client Inquiry</h2>

          <div style="background: #f5f5f5; padding: 16px; border-radius: 8px; margin: 16px 0;">
            <p><strong>Client Name:</strong> ${params.callerName}</p>
            <p><strong>Call Back Number:</strong> <a href="tel:${params.callerPhone}">${params.callerPhone}</a></p>
            ${params.callerEmail ? `<p><strong>Email:</strong> <a href="mailto:${params.callerEmail}">${params.callerEmail}</a></p>` : ''}
            <p><strong>Legal Area:</strong> ${params.legalArea}</p>
          </div>

          ${(params.petitionType || params.urgencyFlag || params.matterCategory || params.partyRole) ? `
            <div style="background: #fff8f0; border-left: 4px solid #f97316; padding: 14px 16px; border-radius: 0 8px 8px 0; margin: 16px 0;">
              <p style="margin: 0 0 8px; font-weight: bold; font-size: 13px; color: #333;">Case Flags</p>
              ${params.petitionType   ? `<p style="margin: 4px 0; font-size: 13px;"><strong>Petition Type:</strong> ${params.petitionType}</p>` : ''}
              ${params.matterCategory ? `<p style="margin: 4px 0; font-size: 13px;"><strong>Matter Category:</strong> ${params.matterCategory}</p>` : ''}
              ${params.partyRole      ? `<p style="margin: 4px 0; font-size: 13px;"><strong>Party Role:</strong> ${params.partyRole}</p>` : ''}
              ${params.urgencyFlag    ? `<p style="margin: 4px 0; font-size: 13px; color: #dc2626;"><strong>⚠ Urgency:</strong> ${params.urgencyFlag}</p>` : ''}
            </div>
          ` : ''}

          <h3 style="color: #333;">Call Summary</h3>
          <p style="line-height: 1.6;">${params.summary}</p>

          ${params.notes ? `
            <h3 style="color: #333;">Notes</h3>
            <p style="line-height: 1.6; white-space: pre-wrap;">${params.notes}</p>
          ` : ''}

          ${pdfBuffer ? `
            <p style="color: #666; font-size: 13px; margin-top: 16px; padding: 12px; background: #f0f7ff; border-radius: 6px;">
              📎 <strong>Full transcript PDF attached</strong> - includes client info, summary, and complete call transcript.
            </p>
          ` : ''}

          ${params.availabilityLink ? `
            <div style="margin: 24px 0;">
              <a href="${params.availabilityLink}"
                 style="background: #2563eb; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; display: inline-block;">
                View Your Availability & Respond
              </a>
            </div>
          ` : ''}

          <p style="color: #666; font-size: 12px; margin-top: 32px;">
            This summary was generated by AI Paralegal. Please review and follow up with the prospective client at your earliest convenience.
          </p>
        </div>
      `,
      ...(pdfBuffer ? {
        attachments: [{
          filename: `${params.callerName.replace(/[^a-zA-Z0-9]/g, '_')}_Transcript_${date.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`,
          content: pdfBuffer,
        }],
      } : {}),
    });

    console.log(`[email] Sent summary${pdfBuffer ? ' with PDF' : ''} to ${params.lawyerEmail} for caller ${params.callerName}`);
    return { success: true };
  } catch (error: any) {
    console.error('[email] Failed to send:', error?.message || error);
    return { success: false, error: error?.message || 'Failed to send email' };
  }
}
