import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

interface CallSummaryEmailParams {
  lawyerEmail: string;
  lawyerName: string;
  callerName: string;
  callerPhone: string;
  callerEmail?: string;
  summary: string;
  notes: string;
  legalArea: string;
  availabilityLink?: string;
}

export async function sendCallSummaryEmail(params: CallSummaryEmailParams): Promise<{ success: boolean; error?: string }> {
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'noreply@example.com';

  try {
    await resend.emails.send({
      from: `AI Paralegal <${fromEmail}>`,
      to: params.lawyerEmail,
      subject: `New Prospective Client: ${params.callerName} - ${params.legalArea}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1a1a1a;">New Prospective Client Inquiry</h2>

          <div style="background: #f5f5f5; padding: 16px; border-radius: 8px; margin: 16px 0;">
            <p><strong>Client Name:</strong> ${params.callerName}</p>
            <p><strong>Call Back Number:</strong> <a href="tel:${params.callerPhone}">${params.callerPhone}</a></p>
            ${params.callerEmail ? `<p><strong>Email:</strong> <a href="mailto:${params.callerEmail}">${params.callerEmail}</a></p>` : ''}
            <p><strong>Legal Area:</strong> ${params.legalArea}</p>
          </div>

          <h3 style="color: #333;">Call Summary</h3>
          <p style="line-height: 1.6;">${params.summary}</p>

          ${params.notes ? `
            <h3 style="color: #333;">Notes</h3>
            <p style="line-height: 1.6;">${params.notes}</p>
          ` : ''}

          ${params.availabilityLink ? `
            <div style="margin: 24px 0;">
              <a href="${params.availabilityLink}"
                 style="background: #2563eb; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; display: inline-block;">
                View Your Availability & Respond
              </a>
            </div>
          ` : ''}

          <p style="color: #666; font-size: 12px; margin-top: 32px;">
            This summary was generated by AI Paralegal. Please review and follow up with the prospective client at your earliest convenience.
          </p>
        </div>
      `,
    });

    console.log(`[email] Sent summary to ${params.lawyerEmail} for caller ${params.callerName}`);
    return { success: true };
  } catch (error: any) {
    console.error('[email] Failed to send:', error?.message || error);
    return { success: false, error: error?.message || 'Failed to send email' };
  }
}
